version: 2.1
jobs:
  build:
    working_directory: ~/go/src/github.com/walkergriggs/openstate
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            make test
